apiVersion: v1
kind: Service
metadata:
  labels:
    app: enginx-service
  name: enginx-service
spec:
  ports:
    - name: service-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: enginx-deployment
  type: NodePort